name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 获取代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: yarn工具安装
        run: npm install pnpm -g

      - name: Build
        run: pnpm install && pnpm build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public