name: Deploy static blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 获取代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: yarn工具安装
        run: npm install -g -yarn&&yarn -v
          
      - name: 展示node版本信息
        run: node -v

      - name: yarn安装依赖包
        run: yarn

      - name: blog编译
        run: yarn build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
